name: My First Workflow

on: push

jobs:
    first_job:
      name: job
      runs-on: ubuntu-latest

      steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: welcome message
        run: |
            echo "My first github actions job"
            ls
            cat README.md

      - name: Generate ascii artwork
        run: cowsay -f dragon "Run....Dragon!" >> dragon.txt

    