name: Generate Ascii Artwork
on: push

jobs:
   build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Execute Cowsay cmd
      run: cowsay -f dragon "Run for cover...dragon" >> dragon.txt
        
    - name: Upload Dragon File
      uses: actions/upload-artifact@v4
      with:
          name: dragon-file
          path: dragon.txt

   test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download Dragon File
      uses: actions/download-artifact@v4
      with:
        name: dragon-file

    - name: Test files Exist
      run: grep -i "dragon" dragon.txt

   deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon File
        uses: actions/download-artifact@v4
        with:
          name: dragon-file

      - name: Read File
        run: cat dragon.txt
    
      - name: Deploy
        run: echo Deploying.....
      
