name: Generate Ascii Artwork
on:
    push
jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: Install cosway Peogram
          run: sudo apt-get install cowsay -y
        - name: Execute cowsay
          run: cowsay -f dragon "Run....Dragon" >> dragon.txt
        - name: Text file exists
          run: grep -i "dragon" dragon.txt
        - name: Read file
          run: cat dragon.txt
        - name: List repo files
          run: ls