name: Generate Ascii Artwork
on: push

jobs:
   build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Execute Cowsay cmd
      run: cowsay -f dragon "Run for cover...dragon" >> dragon.txt
        
    - name: sleep for 30 seconds
      run: sleep 30

   test_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 second
      run: sleep 10

    - name: Test files Exist
      run: grep -i "dragon" dragon.txt

   deploy_job_3:
    runs-on: ubuntu-latest
    steps:
      - name: Read File
        run: cat dragon.txt
    
      - name: Deploy
        run: echo Deploying.....
      
