name: Exploring Variables and Secrets

on: push

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
    docker: 
        runs-on: ubuntu-latest
        steps:
            - name: Docker build 
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

            - name: Docker Login
              run: echo docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
    Deploy:
        runs-on: ubuntu-latest
        needs: docker
        steps:
            - name: Deploy Run
              run: echo docker run -d -p 80:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest